version: '3.9'
services:
  db:
    build: ./my-golang/sql
    image: registry.digitalocean.com/smm2/db-product-1.0
    container_name: db-product
    volumes:
      - /data:/var/lib/postgresql/data
    expose:
      - "${DB_PORT}"
    networks:
      - product-net
  api:
    build: ./my-golang
    image: registry.digitalocean.com/smm2/be-product-1.0
    container_name: be-product
    depends_on:
      - db
    environment:
      - PORT=${API_PORT}
      - DB_HOST=db-product
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - "${API_PORT}:${API_PORT}"
    networks:
      - product-net
  web:
    build: ./my-react
    image: registry.digitalocean.com/smm2/be-product-1.0
    container_name: fe-product
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=be-product
    depends_on:
      - api
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - product-net
networks:
  product-net:
