version: '3.9'
services:
  db:
    build: ./my-golang/sql
    image: mypostgres:1.0
    container_name: mypostgres
    volumes:
      - /data:/var/lib/postgresql/data
    expose:
      - "${DB_PORT}"
    networks:
      - mynet
  api:
    build: ./my-golang
    image: mygolang:1.0
    container_name: mygolang
    depends_on:
      - db
    environment:
      - PORT=${API_PORT}
      - DB_HOST=mypostgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NM}
      - DB_PASSWORD=5mmB2
    expose:
      - "${API_PORT}"
    networks:
      - mynet
  web:
    build: ./my-react
    image: myreact:1.0
    container_name: myreact
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=mygolang
    depends_on:
      - api
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - mynet
networks:
  mynet:
